#!/usr/bin/env python3
"""Read UnresolvedCall targets from a codegen log and emit sized [functions]
entries for them (accumulating into an include file). Iterate codegen+this
until validation is clean.

Targets are branch destinations that aren't in any function (shared tails of
indirect-only gap functions). Size each to the next terminator, capped at the
next known entry to avoid overlap.

Usage: python tools/add_unresolved.py <codegen.log(utf16)> extracted/nhlzf_image.bin \
         app/generated/default/nhl12_init.cpp app/nhl12_extrafuncs.toml
"""
import bisect
import re
import struct
import sys

CODE_BASE, CODE_END, IMAGE_BASE = 0x82580000, 0x836D8BD0, 0x82000000


def is_terminator(w):
    return w == 0x4E800020 or w == 0x4E800420 or ((w >> 26) == 18 and (w & 1) == 0)


def main():
    log_path, img_path, init_path, out_path = sys.argv[1:5]
    data = open(img_path, "rb").read()

    def word(va):
        return struct.unpack_from(">I", data, va - IMAGE_BASE)[0]

    # decode utf-16 log
    raw = open(log_path, "rb").read()
    try:
        text = raw.decode("utf-16-le")
    except Exception:
        text = raw.decode("latin-1")

    new_targets = set()
    for m in re.finditer(r"(0x[0-9A-Fa-f]+) from 0x[0-9A-Fa-f]+: b ", text):
        new_targets.add(int(m.group(1), 16))

    # known entries: registered + already-accumulated extras
    reg = set()
    for m in re.finditer(r"\{\s*(0x[0-9A-Fa-f]+),\s*sub_", open(init_path).read()):
        reg.add(int(m.group(1), 16))
    existing = set()
    try:
        for line in open(out_path):
            m = re.match(r'\s*"(0x[0-9A-Fa-f]+)"', line)
            if m:
                existing.add(int(m.group(1), 16))
    except FileNotFoundError:
        pass

    add = sorted(t for t in new_targets if t not in existing)
    # Emit with NO size: the analyzer CF-scans each entry for its real extent;
    # an explicit cap truncates functions with forward branches (undeclared
    # labels), and a zero-length range avoids the config overlap check.
    lines = [f'"0x{c:08X}" = {{}}\n' for c in add]

    mode = "a" if existing else "w"
    with open(out_path, mode) as f:
        if not existing:
            f.write("# Auto-generated by tools/add_unresolved.py (iterative).\n")
            f.write("# Shared-tail / branch targets of indirect-only gap functions.\n\n")
            f.write("[functions]\n")
        for ln in lines:
            f.write(ln)

    sys.stderr.write(f"added {len(lines)} new entries (of {len(new_targets)} targets) -> {out_path}\n")


if __name__ == "__main__":
    main()
