#!/usr/bin/env python3
"""Find functions the RexGlue analyzer missed because they're reached only via
runtime-constructed pointers (not pdata, not static branch/vtable targets).

Heuristic: an aligned code address C is such a function iff
  - the instruction at C-4 is an unconditional terminator (blr / b / bctr),
    i.e. C is NOT reachable by fall-through, AND
  - C is not a registered function entry, AND
  - C is not padding (00000000 / nop), AND
  - C is not the target of any *static* branch (b/bl/bc...).
That leaves exactly the code entered only through an indirect call.

Emits a TOML [functions] table (address -> size, sized to the next terminator,
capped at the next registered entry to avoid overlap).

Usage: python tools/find_gap_functions.py extracted/nhlzf_image.bin \
         app/generated/default/nhl12_init.cpp app/nhl12_gapfuncs.toml
"""
import re
import struct
import sys

CODE_BASE = 0x82580000
CODE_END = 0x836D8BD0  # from ppc_config.h: PPC_CODE_BASE + PPC_CODE_SIZE
IMAGE_BASE = 0x82000000


def is_terminator(w):
    if w == 0x4E800020:  # blr
        return True
    if w == 0x4E800420:  # bctr
        return True
    if (w >> 26) == 18 and (w & 1) == 0:  # b / ba (unconditional, not bl)
        return True
    return False


def main():
    img_path, init_path, out_path = sys.argv[1], sys.argv[2], sys.argv[3]
    data = open(img_path, "rb").read()

    def word(va):
        off = va - IMAGE_BASE
        return struct.unpack_from(">I", data, off)[0]

    # 1) registered entries
    registered = set()
    for m in re.finditer(r"\{\s*(0x[0-9A-Fa-f]+),\s*sub_", open(init_path).read()):
        registered.add(int(m.group(1), 16))

    # 1b) switch-table labels (handled by the [[switch_tables]] mechanism; do NOT
    # double-register them as standalone functions or they conflict).
    switch_labels = set()
    sw_path = sys.argv[4] if len(sys.argv) > 4 else None
    if sw_path:
        try:
            for line in open(sw_path):
                m = re.match(r"\s*(0x[0-9A-Fa-f]+),\s*$", line)
                if m:
                    switch_labels.add(int(m.group(1), 16))
        except FileNotFoundError:
            pass

    # 2) all static direct branch targets (b/bl opcode 18, bc opcode 16)
    targets = set()
    for va in range(CODE_BASE, CODE_END, 4):
        w = word(va)
        op = w >> 26
        if op == 18:
            li = w & 0x03FFFFFC
            if li & 0x02000000:
                li -= 0x04000000
            tgt = li if (w & 2) else (va + li)
            targets.add(tgt)
        elif op == 16:  # bc
            bd = w & 0xFFFC
            if bd & 0x8000:
                bd -= 0x10000
            tgt = bd if (w & 2) else (va + bd)
            targets.add(tgt)

    # 3) find indirect-only entries
    cands = []
    for va in range(CODE_BASE + 4, CODE_END, 4):
        if not is_terminator(word(va - 4)):
            continue
        if va in registered or va in targets or va in switch_labels:
            continue
        w = word(va)
        if w == 0 or w == 0x60000000:  # padding / nop
            continue
        cands.append(va)

    # 4) Emit entries with NO size: the analyzer scans each entry by control
    # flow to derive its real blocks (covering forward branch targets), and a
    # zero-length config range bypasses the overlap check, so functions with
    # holes / shared tails coexist cleanly. An explicit size only acts as a cap
    # and truncates such functions (-> undeclared labels at compile time).
    entries = sorted(cands)

    with open(out_path, "w") as f:
        f.write("# Auto-generated by tools/find_gap_functions.py.\n")
        f.write("# Functions reached only via runtime-constructed pointers that the\n")
        f.write("# analyzer missed (indirect-only). See script header for the heuristic.\n\n")
        f.write("[functions]\n")
        for c in entries:
            f.write(f'"0x{c:08X}" = {{}}\n')

    sys.stderr.write(f"registered={len(registered)} static_targets={len(targets)} "
                     f"gap_functions={len(entries)} -> {out_path}\n")


if __name__ == "__main__":
    main()
