# package.ps1 - dev-side release pipeline for NHL Legacy Recomp.
#
# Builds the port + packager, generates the payload manifest (pinning the
# vanilla default.xex hash from assets/), stages the end-user layout and
# zips it. PowerShell 5.1 compatible.
#
# Usage:
#   .\release\package.ps1 -Version 0.1.0
#   .\release\package.ps1 -Version 0.1.0 -RunCodegen          # fresh codegen first
#   .\release\package.ps1 -Version 0.1.0 -TestInput "H:\...\NHL Legacy - Vanilla"

[CmdletBinding()]
param(
    [string]$Version   = "0.1.0",
    [string]$Preset    = "win-amd64-relwithdebinfo",
    [string]$SdkDir    = "E:\Tools\rexglue-sdk\0.8.0\win-amd64",
    [string]$LlvmBin   = "C:\Program Files\LLVM\bin",
    [switch]$RunCodegen,             # re-run rexglue codegen before building
    [string]$TestInput = "",         # ISO or extracted folder for the post-zip self-check
    [string]$OutDir    = ""
)

$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent $PSScriptRoot
if (-not $OutDir) { $OutDir = Join-Path $RepoRoot "out\release" }
$BuildDir = Join-Path $RepoRoot "out\build\$Preset"

# Runtime DLL flavor suffix follows the preset. relwithdebinfo ("rd") is the
# only flavor that has been play-tested; switch to release only after a full
# smoke pass.
if ($Preset -like "*relwithdebinfo") { $Flavor = "rd" }
elseif ($Preset -like "*release")    { $Flavor = "" }
elseif ($Preset -like "*debug")      { $Flavor = "d" }
else { throw "Unrecognized preset '$Preset'" }

function Step([string]$Name) {
    Write-Host ""
    Write-Host "=== $Name ===" -ForegroundColor Cyan
}

function CheckExit([string]$What) {
    if ($LASTEXITCODE -ne 0) { throw "$What failed (exit $LASTEXITCODE)" }
}

# --- Toolchain on PATH ---
if (-not (Get-Command clang++ -ErrorAction SilentlyContinue)) {
    $env:PATH = "$LlvmBin;$env:PATH"
}

# --- 1. Codegen (optional; generated/ is normally current in the repo) ---
if ($RunCodegen) {
    Step "rexglue codegen"
    & (Join-Path $SdkDir "bin\rexglue.exe") codegen (Join-Path $RepoRoot "nhllegacy_manifest.toml")
    CheckExit "codegen"
}

# --- 2. Configure + build the port and the packager ---
Step "Configure ($Preset)"
$SdkDirFwd = $SdkDir -replace '\\', '/'
cmake --preset $Preset "-DCMAKE_PREFIX_PATH=$SdkDirFwd"
CheckExit "cmake configure"

Step "Build nhllegacy + nhl-legacy-builder"
cmake --build --preset $Preset --target nhllegacy
CheckExit "build nhllegacy"
cmake --build --preset $Preset --target nhl-legacy-builder
CheckExit "build nhl-legacy-builder"

$PortExe     = Join-Path $BuildDir "nhllegacy.exe"
$BuilderExe  = Join-Path $BuildDir "tools\packager\nhl-legacy-builder.exe"
$RuntimeDll  = "rexruntime$Flavor.dll"
$TracyDll    = "TracyClient$Flavor.dll"
foreach ($f in @($PortExe, $BuilderExe)) {
    if (-not (Test-Path $f)) { throw "Expected build output missing: $f" }
}

# --- 3. Hashes + payload manifest ---
Step "Generate payload manifest"
$XexPath = Join-Path $RepoRoot "assets\default.xex"
$XexHash = (Get-FileHash -Algorithm SHA256 $XexPath).Hash.ToLower()
$XexSize = (Get-Item $XexPath).Length
$ExeHash = (Get-FileHash -Algorithm SHA256 $PortExe).Hash.ToLower()

$ManifestText = @"
# NHL Legacy Recomp payload manifest - generated by release/package.ps1.
# Pins the exact game build this release's port was recompiled from.

[tool]
version      = "$Version"
sdk_version  = "0.8.0"
port_build   = "$Preset"
runtime_dll  = "$RuntimeDll"

[xex]
title        = "NHL Legacy (vanilla)"
sha256       = "$XexHash"
size_bytes   = $XexSize

[port]
exe          = "nhllegacy.exe"
exe_sha256   = "$ExeHash"
"@

# --- 4. Stage the release layout ---
Step "Stage release layout"
$StageName = "nhl-legacy-recomp-$Version"
$Stage     = Join-Path $OutDir $StageName
$Payload   = Join-Path $Stage "payload"
if (Test-Path $Stage) { Remove-Item -Recurse -Force $Stage }
New-Item -ItemType Directory -Force $Payload | Out-Null

# Top level: builder CLI + its runtime DLLs + docs.
Copy-Item $BuilderExe $Stage
Copy-Item (Join-Path $BuildDir "tools\packager\$RuntimeDll") $Stage
Copy-Item (Join-Path $BuildDir "tools\packager\$TracyDll") $Stage
Copy-Item (Join-Path $PSScriptRoot "README.payload.md") (Join-Path $Stage "README.txt")
Copy-Item (Join-Path $PSScriptRoot "THIRD-PARTY-NOTICES.txt") $Stage

# payload/: the prebuilt port + its runtime DLLs + manifest.
Copy-Item $PortExe $Payload
Copy-Item (Join-Path $BuildDir $RuntimeDll) $Payload
Copy-Item (Join-Path $BuildDir $TracyDll) $Payload
# FidelityFX DLLs ship next to the port exe when the runtime uses them.
Get-ChildItem $BuildDir -Filter "amd_fidelityfx*.dll" -ErrorAction SilentlyContinue |
    ForEach-Object { Copy-Item $_.FullName $Payload }
Set-Content -Path (Join-Path $Payload "manifest.toml") -Value $ManifestText -Encoding ascii

# --- 5. Zip ---
Step "Zip"
$ZipPath = Join-Path $OutDir "$StageName.zip"
if (Test-Path $ZipPath) { Remove-Item -Force $ZipPath }
Compress-Archive -Path $Stage -DestinationPath $ZipPath
Write-Host "Release zip: $ZipPath ($([math]::Round((Get-Item $ZipPath).Length / 1MB, 1)) MB)"

# --- 6. Self-check (optional) ---
if ($TestInput) {
    Step "Self-check: verify against $TestInput"
    $CheckDir = Join-Path $env:TEMP "nhl-legacy-release-check"
    if (Test-Path $CheckDir) { Remove-Item -Recurse -Force $CheckDir }
    Expand-Archive -Path $ZipPath -DestinationPath $CheckDir
    $CheckedBuilder = Join-Path $CheckDir "$StageName\nhl-legacy-builder.exe"
    if (Test-Path -PathType Container $TestInput) {
        & $CheckedBuilder verify --from $TestInput
    } else {
        & $CheckedBuilder verify --iso $TestInput
    }
    CheckExit "release self-check"
    Write-Host "Self-check passed." -ForegroundColor Green
}

Write-Host ""
Write-Host "Done: $ZipPath" -ForegroundColor Green
