// nhl-legacy-builder - payload/manifest.toml reader.
//
// The manifest is generated by release/package.ps1 and pins the exact game
// build this release's prebuilt port was recompiled from.

#pragma once

#include <cstdint>
#include <filesystem>
#include <string>

#include "errors.h"

namespace packager {

struct PayloadManifest {
  std::string tool_version;   // [tool] version
  std::string sdk_version;    // [tool] sdk_version
  std::string port_build;     // [tool] port_build (CMake preset name)
  std::string xex_title;      // [xex] title (display only)
  std::string xex_sha256;     // [xex] sha256, lowercase hex
  uint64_t xex_size_bytes = 0;  // [xex] size_bytes (fast pre-check)
  std::string port_exe;       // [port] exe, e.g. "nhllegacy.exe"
};

// Minimal TOML subset reader ([section], key = "string" | integer). Enough
// for the manifest we generate ourselves; avoids a third-party dependency.
bool LoadPayloadManifest(const std::filesystem::path& path,
                         PayloadManifest& out, Error& err);

}  // namespace packager
